[package]
name = "zkp_auth"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tonic-build = "0.9"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"]}
hex = "0.4.3"

